# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
    configs:
        main_config:
            allowedContent: true # Désactive le filtrage dans le code source, par exemple sur l'ajout de propriété HTML
            height: 850 # Hauteur
            width: 1000 # Largeur 
            toolbar: full

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
